version: '1'
services:
  run-spring:
    container_name: run-spring
    build:
      context: .
      dockerfile: Dockerfile
    image: run-spring:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
