version: '1'
services:
  rule-spring:
    container_name: rule-spring
    build:
      context: .
      dockerfile: Dockerfile
    image: rule-spring:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
