spring:
    datasource:
        url: jdbc:h2:mem:mydb2
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
            path: /h2
custom:
    ruleTemplate: /home/pc7/IdeaProjects/modular-rule-engine/modular-rule-engine-backend/src/main/resources/ruleTemplate.java